name: Publish On NuGet

on:
  push:
    branches:
      - master
    tags:
      - '*' # Push version tags matching to *, i.e. v1.0.0, 20.15.10 

jobs:
  publish:
    name: List on NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build --configuration Release "Lykke.Cqrs.sln"
      - name: Create the package
        run: dotnet pack --include-symbols --include-source --configuration Release src/Lykke.Cqrs/Lykke.Cqrs.csproj /p:Version=${GITHUB_REF#refs/tags/}
      - name: Publish the package to GPR
        run: dotnet nuget push src/Lykke.Cqrs/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
